### ISSUE TITLE
auto-update app so i dont have to download new release

### ISSUE THREAD

**Issue by rustyfausak** [tfausak/gizmo-gg-uploader#3]

**Comment by tfausak** [comment]
Everything is in place for this, but for some reason the auto updater is looking for the wrong tag name.

> Cannot find `latest.yml` in the latest release artifacts (`https://github.com/tfausak/gizmo-gg-uploader/releases/download/v0.0.5/latest.yml`): HttpError: 404 Not Found

It should be looking for the tag `0.0.5` instead of `v0.0.5`.
